name: XenonbanBackend
version: 0
main: ir.realstresser.xenonbanbackend.XenonBanBackend
commands:
  ban:
    permission: xenonban.ban
  kick:
    permission: xenonban.kick
  mute:
    permission: xenonban.mute
